{% set name = "pyproject-parser" %}
{% set version = "0.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: ff1ddb5d426c6d8b38ad73cda2d5caf3f568852cb4e0cf869345c89e8ca0fb76

build:
  entry_points:
    - pyproject-parser=pyproject_parser.__main__:main
    - check-pyproject=pyproject_parser.__main__:check
    - pyproject-fmt=pyproject_parser.__main__:reformat
    - pyproject-info=pyproject_parser.__main__:info
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - hatchling
    - hatch-requirements-txt
    - pip
    - python {{ python_min }}
  run:
    - apeye-core >=1.0.0
    - attrs >=20.3.0
    - click >=7.1.2
    - consolekit >=1.4.1
    - dom-toml >=2.0.0
    - domdf-python-tools >=2.8.0
    - natsort >=7.1.1
    - packaging >=20.9
    - python >={{ python_min }}
    - shippinglabel >=1.0.0
    - typing-extensions !=4.7.0,>=3.7.4.3
  run_constrained:
    - sdjson >=0.3.1

test:
  imports:
    - pyproject_parser
  commands:
    - pip check
    - pyproject-parser --help
    - check-pyproject --help
    - pyproject-fmt --help
    - pyproject-info --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/repo-helper/pyproject-parser
  summary: Parser for 'pyproject.toml'
  license: MIT
  license_file: LICENSE
  doc_url: https://pyproject-parser.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - domdfcoding
