{% set name = "pyproject-parser" %}
{% set version = "0.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: ff1ddb5d426c6d8b38ad73cda2d5caf3f568852cb4e0cf869345c89e8ca0fb76

build:
  number: 0
  entry_points:
    - pyproject-parser=pyproject_parser.__main__:main
    - check-pyproject=pyproject_parser.__main__:check
    - pyproject-fmt=pyproject_parser.__main__:reformat
    - pyproject-info=pyproject_parser.__main__:info
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: True  # [py<37]

requirements:
  host:
    - python
    - pip
    - hatchling
    - hatch-requirements-txt
  run:
    - apeye-core >=1.0.0
    - attrs >=20.3.0
    - dom-toml >=2.0.0
    - domdf-python-tools >=2.8.0
    - natsort >=7.1.1
    - packaging >=20.9
    - python
    - shippinglabel >=1.0.0
    - typing-extensions !=4.7.0,>=3.7.4.3
    # click and consolekit not in the run_constrained because upstream developer move it in run in the conda-forge.
    - click >=7.1.2,<8.2
    - consolekit >=1.4.1
  run_constrained:
    - sdjson >=0.3.1

# We can`t enable pytest because conftest uses the coincidence package, which is unavailable on the main channel.
# The policy states that packages are not specifically built for testing.
test:
  imports:
    - pyproject_parser
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pyproject-parser --help
    - check-pyproject --help
    - pyproject-fmt --help
    - pyproject-info --help
  requires:
    - pip

about:
  home: https://github.com/repo-helper/pyproject-parser
  summary: Parser for 'pyproject.toml'
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: Parser for 'pyproject.toml'
  doc_url: https://pyproject-parser.readthedocs.io
  dev_url: https://github.com/repo-helper/pyproject-parser

extra:
  recipe-maintainers:
    - domdfcoding
